//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace advt.CMS.MESWebService {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MESWebService.ETL_ServiceSoap")]
    public interface ETL_ServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ETL_Rv", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ETL_Rv(string sParam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ETL_Rv", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ETL_RvAsync(string sParam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ETL_Tx", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ETL_Tx(string sParam, string sType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ETL_Tx", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ETL_TxAsync(string sParam, string sType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SFIS_Rv_Xml", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SFIS_Rv_Xml(string sParam, string sWebServiceType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SFIS_Rv_Xml", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SFIS_Rv_XmlAsync(string sParam, string sWebServiceType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SFIS_Rv", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet SFIS_Rv(string sParam, string sWebServiceType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SFIS_Rv", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> SFIS_RvAsync(string sParam, string sWebServiceType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SFIS_Tx", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SFIS_Tx(string sParam, string sType, string sWebServiceType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SFIS_Tx", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SFIS_TxAsync(string sParam, string sType, string sWebServiceType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MMS_RV", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet MMS_RV(string sParam, string sWebServiceType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MMS_RV", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> MMS_RVAsync(string sParam, string sWebServiceType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MMS_TX", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string MMS_TX(string sParam, string sWebServiceType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MMS_TX", ReplyAction="*")]
        System.Threading.Tasks.Task<string> MMS_TXAsync(string sParam, string sWebServiceType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SFIS_Tx_ALL", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int SFIS_Tx_ALL(string sParam, string sType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SFIS_Tx_ALL", ReplyAction="*")]
        System.Threading.Tasks.Task<int> SFIS_Tx_ALLAsync(string sParam, string sType);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ETL_ServiceSoapChannel : advt.CMS.MESWebService.ETL_ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ETL_ServiceSoapClient : System.ServiceModel.ClientBase<advt.CMS.MESWebService.ETL_ServiceSoap>, advt.CMS.MESWebService.ETL_ServiceSoap {
        
        public ETL_ServiceSoapClient() {
        }
        
        public ETL_ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ETL_ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ETL_ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ETL_ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet ETL_Rv(string sParam) {
            return base.Channel.ETL_Rv(sParam);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ETL_RvAsync(string sParam) {
            return base.Channel.ETL_RvAsync(sParam);
        }
        
        public string ETL_Tx(string sParam, string sType) {
            return base.Channel.ETL_Tx(sParam, sType);
        }
        
        public System.Threading.Tasks.Task<string> ETL_TxAsync(string sParam, string sType) {
            return base.Channel.ETL_TxAsync(sParam, sType);
        }
        
        public string SFIS_Rv_Xml(string sParam, string sWebServiceType) {
            return base.Channel.SFIS_Rv_Xml(sParam, sWebServiceType);
        }
        
        public System.Threading.Tasks.Task<string> SFIS_Rv_XmlAsync(string sParam, string sWebServiceType) {
            return base.Channel.SFIS_Rv_XmlAsync(sParam, sWebServiceType);
        }
        
        public System.Data.DataSet SFIS_Rv(string sParam, string sWebServiceType) {
            return base.Channel.SFIS_Rv(sParam, sWebServiceType);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SFIS_RvAsync(string sParam, string sWebServiceType) {
            return base.Channel.SFIS_RvAsync(sParam, sWebServiceType);
        }
        
        public string SFIS_Tx(string sParam, string sType, string sWebServiceType) {
            return base.Channel.SFIS_Tx(sParam, sType, sWebServiceType);
        }
        
        public System.Threading.Tasks.Task<string> SFIS_TxAsync(string sParam, string sType, string sWebServiceType) {
            return base.Channel.SFIS_TxAsync(sParam, sType, sWebServiceType);
        }
        
        public System.Data.DataSet MMS_RV(string sParam, string sWebServiceType) {
            return base.Channel.MMS_RV(sParam, sWebServiceType);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> MMS_RVAsync(string sParam, string sWebServiceType) {
            return base.Channel.MMS_RVAsync(sParam, sWebServiceType);
        }
        
        public string MMS_TX(string sParam, string sWebServiceType) {
            return base.Channel.MMS_TX(sParam, sWebServiceType);
        }
        
        public System.Threading.Tasks.Task<string> MMS_TXAsync(string sParam, string sWebServiceType) {
            return base.Channel.MMS_TXAsync(sParam, sWebServiceType);
        }
        
        public int SFIS_Tx_ALL(string sParam, string sType) {
            return base.Channel.SFIS_Tx_ALL(sParam, sType);
        }
        
        public System.Threading.Tasks.Task<int> SFIS_Tx_ALLAsync(string sParam, string sType) {
            return base.Channel.SFIS_Tx_ALLAsync(sParam, sType);
        }
    }
}
